schema_version: 1

context:
  name: pydantic-extra-types
  version: 2.11.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pydantic_extra_types-${{ version }}.tar.gz
  sha256: 4e9991959d045b75feb775683437a97991d02c138e00b59176571db9ce634f0e

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - pydantic >=2.5.2
  run_constraints:
    - phonenumbers >=8,<9
    - pycountry >=23
    - semver >=3.0.2,<4
    - python-ulid >=1,<3
    - pendulum >=3.0.0,<4.0.0
    - pytz >=2024.1
    - tzdata >=2024a

tests:
  - python:
      imports:
        - pydantic_extra_types
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  license: MIT
  license_file: LICENSE
  summary: A place for pydantic types that probably shouldn't exist in the main pydantic lib.
  homepage: https://github.com/pydantic/pydantic-extra-types
  repository: https://github.com/pydantic/pydantic-extra-types
  documentation: https://docs.pydantic.dev/

extra:
  recipe-maintainers:
    - ytausch
